version: '3.1'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=OnlineApp_prod
    ports:
      # port exposed : mysql port running inside container
      - "3308:3306"

  app:
    build: ../../
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/OnlineApp_prod?autoReconnect=true&useSSL=false
    depends_on:
      - db