
services:
  db-prod:
    image: mysql:8
    restart: always
    container_name: db-prod
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=OnlineApp_prod
    ports:
      # port exposed : mysql port running inside container
      - "3308:3306"


  app:
    build: ../../
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-prod:3306/OnlineApp_prod?autoReconnect=true
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db-prod
    entrypoint: ["sh", "-c", "/wait-for-it.sh db-prod:3306 -- java -jar /app.jar"]