version: '3.1'

services:
  db-dev:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # port exposed : mysql port running inside container
      - "3307:3306"
    volumes:
      - ./schema-dev.sql:/docker-entrypoint-initdb.d/ddbschema.sql
